accounts/urls.py
from django.urls import path

from accounts.views import UserCreateView, UserLoginView, UserLogoutView

app_name = "accounts"

urlpatterns = [
    path("register/", UserCreateView.as_view(), name="register"),
    path("login/", UserLoginView.as_view(), name="login"),
    path("logout/", UserLogoutView.as_view(), name="logout"),
]

music/urls.py
from django.urls import path
from music.views import CreateArtistView, CreateSongView, ListArtistView, ListSongView

app_name = "music"

urlpatterns = [
    path("all-songs/", ListSongView.as_view(), name="all_songs"),
    path("all-artists/", ListArtistView.as_view(), name="all_artists"),
    path("add-artist/", CreateArtistView.as_view(), name="add_artist"),
    path("add-song/", CreateSongView.as_view(), name="add_song"),
]

symfoni/urls.py
from django.contrib import admin
from django.urls import include, path

from symfoni.views import home_page

urlpatterns = [
    path("admin/", admin.site.urls),
    path("music/", include("music.urls")),
    path("", home_page, name="home_page"),
    path("accounts/", include("accounts.urls")),
]

music/models.py
from django.contrib.auth import get_user_model
from django.db import models
from uuid import uuid4

User = get_user_model()


class Artist(models.Model):
    name = models.CharField(max_length=50, null=False)
    added_by = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"Artist named {self.name}"


class Song(models.Model):
    name = models.CharField(max_length=50, null=False)
    artists = models.ManyToManyField(Artist, related_name="artists", blank=True)
    added_by = models.ForeignKey(User, on_delete=models.CASCADE)
    url = models.URLField()
    users_who_liked = models.ManyToManyField(
        User, related_name="users_who_liked", blank=True
    )

    def __str__(self) -> str:
        if self.artists.count() == 0:
            return self.name
        artists_names = map(lambda s: s.name, self.artists.all())
        names = ", ".join(artists_names)
        return f"{self.name} by {names}"


class Playlist(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid4, editable=False)
    name = models.CharField(max_length=75, null=False)
    songs = models.ManyToManyField(Song, related_name="songs", blank=True)
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    def __str__(self) -> str:
        if self.songs.count() == 0:
            return self.name
        song_names = map(lambda s: s.name, self.songs.all())
        names = ", ".join(song_names)
        return f"{self.name} containing {names}"

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

User = get_user_model()


class RegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = [
            "username",
            "email",
            "password1",
            "password2",
            "first_name",
            "last_name",
        ]

music/forms.py
from django import forms

accounts/views.py
from accounts.forms import RegistrationForm
from django.views.generic import CreateView
from django.contrib.auth import get_user_model
from django.urls import reverse_lazy
from django.contrib.auth.views import LoginView, LogoutView

User = get_user_model()


# Create your views here.


class UserCreateView(CreateView):
    template_name = "accounts/register.html"
    form_class = RegistrationForm
    success_url = reverse_lazy("home_page")


class UserLoginView(LoginView):
    template_name = "accounts/login.html"


class UserLogoutView(LogoutView):
    template_name = "accounts/logout.html"

music/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView

from music.models import Artist, Song


class ListSongView(ListView):
    template_name = "music/all-songs.html"
    model = Song


class ListArtistView(ListView):
    template_name = "music/all-artists.html"
    model = Artist


class CreateArtistView(CreateView):
    template_name = "music/add-artist.html"
    model = Artist
    fields = ["name"]
    success_url = reverse_lazy("music:all_artists")

    def form_valid(self, form, *args, **kwargs):
        # artist = Artist.objects.create(
        #     name="qdwefsdgbgfnhjdwfsbg",
        #     artist="ed",
        #     added_by="Chayanika"
        # )
        # artist.save() # this is not called when you pass commit=False
        artist = form.save(commit=False)
        artist.added_by = self.request.user  # this is the currently logged in user
        artist.save()
        return super().form_valid(form, *args, **kwargs)


class CreateSongView(CreateView):
    template_name = "music/add-song.html"
    model = Song
    fields = ["name", "url", "artists"]
    success_url = reverse_lazy("music:all_songs")

    def form_valid(self, form, *args, **kwargs):
        # song = Song.objects.create(
        #     name="qdwefsdgbgfnhjdwfsbg",
        #     url="https://wM&usg=AOvVaw3",
        #     artist="ed",
        #     added_by="Chayanika"
        # )
        # song.save() # this is not called when you pass commit=False
        song = form.save(commit=False)
        song.added_by = self.request.user  # this is the currently logged in user
        song.save()
        return super().form_valid(form, *args, **kwargs)


# def add_artist_view(request):  # function based view
#     if request.method == "GET":
#         print("request-method: ", request.method)
#         form = ArtistForm()
#         return render(request, "music/add-artist.html", {"form": form})
#     artist_name = request.POST["name"]
#     artist = Artist.objects.create(name=artist_name)
#     artist.save()
#     return redirect(reverse("music:all_artists"))

symfoni/views.py
from django.shortcuts import render


# Create your views here.
def home_page(request):
    context_dictionary = {}
    return render(request, "home-page.html", context_dictionary)

accounts/templates/accounts/login.html
{% extends 'base.html' %} {% load bulma_tags %}

<!-- page title -->
{% block document_title %} Login {% endblock %}

<!-- main content -->

{% block main_content %}
<div
  class="
    is-flex
    is-flex-grow-1
    is-align-content-center
    is-justify-content-center
    is-flex-direction-column
  "
>
  <h1 class="title is-1 has-text-centered">Login</h1>
  <div class="columns is-centered block mt-5">
    <form
      method="POST"
      class="column is-half is-flex-direction-column columns block"
    >
      {% csrf_token %}
      <div class="block">{{ form | bulma }}</div>
      <button
        class="button is-success is-medium column is-full block"
        type="submit"
        value="Submit"
      >
        Login
      </button>
    </form>
  </div>
  <div class="has-text-centered">
    Accounts does not exist? Register
    <a href="{% url 'accounts:register' %}">here.</a>
  </div>
</div>
{% endblock %}

accounts/templates/accounts/logout.html
<h1> Thank you for using our app. You have been logged out successfuly.</h1>

accounts/templates/accounts/register.html
{% extends 'base.html' %}

<!-- page title -->
{%  block document_title %}
Register
{% endblock %}

<!-- start content -->
{% block main_content %}
<h1>Create an account.</h1>
<form method="POST">
  {% csrf_token %}
  <div>{{ form.as_p }}</div>
  <button type="submit" value="Submit">Create account</button>
</form>
{% endblock %}

accounts/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block document_title %} {% endblock %}</title>
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css"
    />
  </head>
  <body
    style="min-height: 100vh"
    class="is-flex is-flex-direction-column container"
  >
    <nav>Symfoni Website hello world</nav>
    <main class="is-flex-grow-1 is-flex">
      {% block main_content %}
      <!-- main content goes here -->
      {% endblock %}
    </main>
  </body>
</html>

music/templates/home-page.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Symfoni</title>
  </head>
  <body>
    <h1 style="font-size: 72px; text-align: center; color: #a317d1">Symfoni</h1>
    <h2>Welcome to the Symfoni Music app, nice to see you here!</h2>
  </body>
</html>

music/templates/music/add-artist.html
<h1>Add a new artist</h1>

<form method="POST">
  {% csrf_token %}
  <div>{{ form.as_p }}</div>
  <button type="submit" value="Submit">Add an artist</button>
</form>

music/templates/music/add-song.html
<h1>Add a new Song</h1>

<form method="POST">
  {% csrf_token %}
  <div>{{ form.as_p }}</div>
  <button type="submit" value="Submit">Add a Song</button>
</form>

<div>
  Didn't find the artist you like? Add one
  <a href="{% url 'music:add_artist' %}">here</a>
</div>

music/templates/music/all-artists.html
<h1>Hello here are all artists</h1>
<div>
  {% for artist in object_list %}
  <div>
    <span>ID: {{ artist.pk }}</span>,
    <span>name: {{ artist.name }}</span>
  </div>
  {% endfor %}
  <a href="{% url 'music:add_artist' %}">Add a new artist</a>
</div>

music/templates/music/all-songs.html
<h1>Hello here are all songs</h1>
<div>
  {% for song in object_list %}
  <div>
    <span>ID: {{ song.pk }}</span>,
    <span>
      name: <a href="{{ song.url }}" target="_blank">{{ song.name }}</a> </span>
    {% if song.artists.count > 0 %}
    <span>
      artists:
      {% for artist in song.artists.all %}
      <span> {{ artist.name }} </span>,
      {% endfor %}
    </span>
    {% endif %}
  </div>
  {% empty %}
  <div> No songs are available as of now. </div>
  {% endfor %}
  <a href="{% url 'music:add_song' %}">Add a new song</a>
</div>